In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.plotly as py
import plotly.tools as pytl
from config import api_key
from config import username
pytl.set_credentials_file(username=username, api_key=api_key)

In [2]:
file = "Resources/statistics.csv"
psych_df = pd.read_csv(file, encoding="utf-8")
psych_df.head()
psych_df["measure_name"].unique()

array(['Deaths', 'YLDs (Years Lived with Disability)',
       'YLLs (Years of Life Lost)', 'Prevalence', 'Incidence',
       'DALYs (Disability-Adjusted Life Years)'], dtype=object)

In [3]:
YLL_group = psych_df.groupby("measure_name")
YLL_only = psych_df.loc[psych_df["measure_name"] == "YLLs (Years of Life Lost)"]
YLL_only.head()
YLL_only_cleaned = YLL_only[["location_name", "sex_name", "age_name", "cause_name", "metric_name", "val"]]
YLL_only_cleaned.head(30)
YLL_number = YLL_only_cleaned.loc[YLL_only_cleaned["metric_name"] == "Number"]
YLL_number.head()
YLL_number_cleaned = YLL_number[["location_name", "sex_name", "age_name", "cause_name", "val"]]
YLL_number_statesort = YLL_number_cleaned.sort_values("location_name", ascending=True)
YLL_number_statesort.head()
YLL_number_statesort.to_csv("output_CSVs/cleaned_YLL.csv", encoding="utf-8", index=False)

In [4]:
YLL_number_statesort

,location_name,sex_name,age_name,cause_name,val
28562,Alabama,Female,60 to 64,Alcohol use disorders,134.331887
54437,Alabama,Male,35 to 39,Substance use disorders,6156.921305
54438,Alabama,Female,35 to 39,Substance use disorders,3620.912936
54443,Alabama,Male,40 to 44,Substance use disorders,4913.513333
54444,Alabama,Female,40 to 44,Substance use disorders,3349.800930
54449,Alabama,Male,45 to 49,Substance use disorders,4518.062818
54450,Alabama,Female,45 to 49,Substance use disorders,3645.351956
54455,Alabama,Male,50 to 54,Substance use disorders,3854.580352
54456,Alabama,Female,50 to 54,Substance use disorders,2986.107592
54461,Alabama,Male,55 to 59,Substance use disorders,2773.346804
54462,Alabama,Female,55 to 59,Substance use disorders,2040.719748
54467,Alabama,Male,60 to 64,Substance use disorders,1447.949124
54468,Alabama,Female,60 to 64,Substance use disorders,1005.749589
54473,Alabama,Male,65 to 69,Substance use disorders,682.230536
54474,Alabama,Female,65 to 69,Substance use disorders,465.254993
54479,Alabama,Male,70 to 74,Substance use disorders,324.059776
54480,Alabama,Female,70 to 74,Substance use disorders,251.326118
54485,Alabama,Male,75 to 79,Substance use disorders,167.397793
54432,Alabama,Female,30 to 34,Substance use disorders,3563.698952
54486,Alabama,Female,75 to 79,Substance use disorders,151.208652
54426,Alabama,Female,25 to 29,Substance use disorders,2840.831350
54420,Alabama,Female,20 to 24,Substance use disorders,1738.823226
28915,Alabama,Male,55 to 59,Amphetamine use disorders,67.678156
28910,Alabama,Female,50 to 54,Amphetamine use disorders,58.698846
28909,Alabama,Male,50 to 54,Amphetamine use disorders,102.988649
28904,Alabama,Female,45 to 49,Amphetamine use disorders,70.430377
28903,Alabama,Male,45 to 49,Amphetamine use disorders,96.691831
28898,Alabama,Female,40 to 44,Amphetamine use disorders,66.270860
28897,Alabama,Male,40 to 44,Amphetamine use disorders,101.294873
28892,Alabama,Female,35 to 39,Amphetamine use disorders,74.309277
...,...,...,...,...,...
112614,Wyoming,Male,60 to 64,Other drug use disorders,15.832326
112609,Wyoming,Female,55 to 59,Other drug use disorders,44.136291
112603,Wyoming,Female,50 to 54,Other drug use disorders,60.539078
112602,Wyoming,Male,50 to 54,Other drug use disorders,39.090433
112597,Wyoming,Female,45 to 49,Other drug use disorders,63.987882
112596,Wyoming,Male,45 to 49,Other drug use disorders,47.891080
112591,Wyoming,Female,40 to 44,Other drug use disorders,64.640436
112590,Wyoming,Male,40 to 44,Other drug use disorders,54.878441
112585,Wyoming,Female,35 to 39,Other drug use disorders,77.235589
112584,Wyoming,Male,35 to 39,Other drug use disorders,64.139465
112579,Wyoming,Female,30 to 34,Other drug use disorders,83.944788
112578,Wyoming,Male,30 to 34,Other drug use disorders,77.904054
112626,Wyoming,Male,70 to 74,Other drug use disorders,6.813939
112573,Wyoming,Female,25 to 29,Other drug use disorders,52.837702
112567,Wyoming,Female,20 to 24,Other drug use disorders,28.555945
112566,Wyoming,Male,20 to 24,Other drug use disorders,48.827113
112561,Wyoming,Female,15 to 19,Other drug use disorders,9.998245
112560,Wyoming,Male,15 to 19,Other drug use disorders,16.108094
112555,Wyoming,Female,80 to 84,Amphetamine use disorders,0.004198
112554,Wyoming,Male,80 to 84,Amphetamine use disorders,0.034142
112549,Wyoming,Female,80 plus,Amphetamine use disorders,0.007286
112548,Wyoming,Male,80 plus,Amphetamine use disorders,0.061655
112543,Wyoming,Female,75 to 79,Amphetamine use disorders,0.085495
112542,Wyoming,Male,75 to 79,Amphetamine use disorders,0.159850
112537,Wyoming,Female,70 to 74,Amphetamine use disorders,0.173165
112536,Wyoming,Male,70 to 74,Amphetamine use disorders,0.319393
112531,Wyoming,Female,65 to 69,Amphetamine use disorders,0.930628
112530,Wyoming,Male,65 to 69,Amphetamine use disorders,1.779200
112572,Wyoming,Male,25 to 29,Other drug use disorders,69.043713
112608,Wyoming,Male,55 to 59,Other drug use disorders,26.657961

In [5]:
alabama = YLL_number_statesort.loc[YLL_number_statesort["location_name"] == "Alabama"]
alabama
sums = alabama["val"].sum()
sums

202536.89450275275

In [6]:
alaska = YLL_number_statesort.loc[YLL_number_statesort["location_name"] == "Alaska"]
sums = alaska["val"].sum()
sums

35573.32085013478

In [7]:
total_YLL = []
for state in YLL_number_statesort["location_name"].unique():
    locator = YLL_number_statesort.loc[YLL_number_statesort["location_name"] == state]
    sums = round(locator["val"].sum(),1)
    total_YLL.append(sums)
total_YLL

[202536.9,
 35573.3,
 249389.4,
 81269.8,
 878335.4,
 159679.8,
 110526.3,
 36157.8,
 18866.0,
 692897.1,
 299419.7,
 23042.4,
 42746.8,
 334113.8,
 238126.5,
 56814.2,
 71569.3,
 272945.2,
 187594.7,
 51059.2,
 90056.9,
 244567.4,
 380566.7,
 96826.9,
 116049.8,
 223861.0,
 36846.5,
 27610.6,
 124349.4,
 56706.0,
 237012.0,
 108137.1,
 444441.9,
 324179.2,
 12701.1,
 558669.1,
 185454.3,
 129431.8,
 546866.2,
 39862.2,
 178171.2,
 15327.6,
 324836.8,
 607737.6,
 92582.4,
 16377.5,
 195684.5,
 224512.9,
 148374.1,
 156097.5,
 22443.3]

In [8]:
unique = YLL_number_statesort["location_name"].unique()
YLL_df = pd.DataFrame({"State": unique,
                             "YLLs (Years of Life Lost)": total_YLL}, index=None)

In [9]:
YLL_df
YLL_df.to_csv("cleaned_total_YLL.csv", encoding="utf-8", index=False)
sorted_YLL = YLL_df.sort_values(by=["State"], ascending=True)
sorted_YLL.head()

        State  YLLs (Years of Life Lost)
0     Alabama                   202536.9
1      Alaska                    35573.3
2     Arizona                   249389.4
3    Arkansas                    81269.8
4  California                   878335.4

In [10]:

state_abbr = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
            "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
state_df = pd.DataFrame({
    "Abbreviation": state_abbr
})

merged_YLL = pd.DataFrame({
    "State": sorted_YLL["State"],
    "Abbreviation": state_df["Abbreviation"],
    "YLL": sorted_YLL["YLLs (Years of Life Lost)"]
})
merged_YLL.to_csv("output_CSVs/cleaned_YLL_sorted.csv", encoding='utf-8')
merged_YLL

                   State Abbreviation       YLL
0                Alabama           AL  202536.9
1                 Alaska           AK   35573.3
2                Arizona           AZ  249389.4
3               Arkansas           AR   81269.8
4             California           CA  878335.4
5               Colorado           CO  159679.8
6            Connecticut           CT  110526.3
7               Delaware           DC   36157.8
8   District of Columbia           DE   18866.0
9                Florida           FL  692897.1
10               Georgia           GA  299419.7
11                Hawaii           HI   23042.4
12                 Idaho           ID   42746.8
13              Illinois           IL  334113.8
14               Indiana           IN  238126.5
15                  Iowa           IA   56814.2
16                Kansas           KS   71569.3
17              Kentucky           KY  272945.2
18             Louisiana           LA  187594.7
19                 Maine           ME   51059.2
20              Maryland           MD   90056.9
21         Massachusetts           MA  244567.4
22              Michigan           MI  380566.7
23             Minnesota           MN   96826.9
24           Mississippi           MS  116049.8
25              Missouri           MO  223861.0
26               Montana           MT   36846.5
27              Nebraska           NE   27610.6
28                Nevada           NV  124349.4
29         New Hampshire           NH   56706.0
30            New Jersey           NJ  237012.0
31            New Mexico           NM  108137.1
32              New York           NY  444441.9
33        North Carolina           NC  324179.2
34          North Dakota           ND   12701.1
35                  Ohio           OH  558669.1
36              Oklahoma           OK  185454.3
37                Oregon           OR  129431.8
38          Pennsylvania           PA  546866.2
39          Rhode Island           RI   39862.2
40        South Carolina           SC  178171.2
41          South Dakota           SD   15327.6
42             Tennessee           TN  324836.8
43                 Texas           TX  607737.6
44                  Utah           UT   92582.4
45               Vermont           VT   16377.5
46              Virginia           VA  195684.5
47            Washington           WA  224512.9
48         West Virginia           WV  148374.1
49             Wisconsin           WI  156097.5
50               Wyoming           WY   22443.3

In [11]:
for col in merged_YLL:
    merged_YLL[col] = merged_YLL[col].astype(str)

scl = [[0.0, 'rgb(242,240,247)'],[0.2, 'rgb(218,218,235)'],[0.4, 'rgb(188,189,220)'],\
            [0.6, 'rgb(158,154,200)'],[0.8, 'rgb(117,107,177)'],[1.0, 'rgb(84,39,143)']]

merged_YLL['text'] = merged_YLL["Abbreviation"] + '<br>' +\
    '"YLLs (Years of Life Lost)" '+merged_YLL["YLL"]

data = [ dict(
        type='choropleth',
        colorscale = scl,
        autocolorscale = False,
        locations = merged_YLL["Abbreviation"],
        z = merged_YLL["YLL"].astype(float),
        locationmode = 'USA-states',
        text = merged_YLL['text'],
        marker = dict(
            line = dict (
                color = 'rgb(255,255,255)',
                width = 2
            )
        ),
        colorbar = dict(
            title = "YLLs (Years of Life Lost)"
        )
    ) ]

layout = dict(
        title = '2017 US Mental Illness: YLLs (Years of Life Lost)',
        geo = dict(
            scope='usa',
            projection=dict( type='albers usa' ),
            showlakes = True,
            lakecolor = 'rgb(255, 255, 255)',
        ),
    )

fig6 = dict( data=data, layout=layout )

url6 = py.plot( fig6, filename='YLL' )
url6

'https://plot.ly/~bkcenik/12'

In [12]:
print(f"YLL data is located at https://plot.ly/~bkcenik/18")

YLL data is located at https://plot.ly/~bkcenik/18